### PR TITLE
fixes for memory and error status leaks in parse cert

### PR DESCRIPTION
**Pull request by astitt-ripple**
While testing this module, I found some issues with memory leaking from the parseCert method (one was already fixed in 3.1, but I found others).

I also found that ssl error statuses are not always cleared. Under the right circumstances the uncleared errors are picked up by other parts of node.js that also use openssl. This can cause some unintended (and sometimes spectacular) side-effects.

@Southern

### CODE REVIEW

**Comment by Southern** [comment]
Thanks for reopening this, and apologies for it taking so long to get back to you.

This looks perfectly fine to me. Going to merge it in and will release it in 0.3.2 some time this week, most likely on Friday.

**Comment by astitt-ripple** [comment]
Thank you @Southern.

There is also https://github.com/Southern/node-x509/pull/47 from my prior PR, which adds some new functionality.

**Comment by Southern** [comment]
Yup. Gonna check that one out too and hopefully get it in 0.3.2 on Friday as well. :)

**Comment by Southern** [comment]
Just an update, didn't forget about this. Had some stuff come up that prevented me from getting to it on Friday. 0.3.2 should now be on NPM.

**Comment by Southern** [comment]
My apologies, @astitt-ripple. I got a new job right after I sent you the last message and have been totally swamped with it.

**Pull request merged**
