### PR TITLE
Fix issue with building x509 on Node.js 12

### PR DESCRIPTION
**Pull request by ghaiklor**
@codebling I made a PR without noise in hope that it can be merged (hoping again?)

@Southern

### CODE REVIEW

**Review by codebling — APPROVED** [review]
:+1:  Looks good to me!!

**Comment by codebling** [comment]
This PR replaces #82. 

Hopefully we can merge this @Southern @yorkie ?

**Comment by yilinglu** [comment]
🙏 Please merge this PR if all looks good!

**Comment by Barsovich** [comment]
Can this PR please be merged? 🙏

**Comment by codebling** [comment]
> Can this PR please be merged?

No contributions to this repo in the past year and 2 the whole year before that, think we should just fork. Use @ghaiklor 's fork

**Pull request closed without merging**
