### PR TITLE
Bump version nan to 2.2.0

### LINKED ISSUE #32: Bump version of nan
Hi,

Currently, this package doesn't work with node v6.x because the version of nan is not compatible, the compilation will exit because of a missing named type in v8::Isolate

Bumping nan to v2.2.0 fixed the problem. I can create a pr if you wish?

Regards

### PR DESCRIPTION
**Pull request by tanuck**
Enable support for node v6.x

Fixes #32

### CODE REVIEW

**Comment by yorkie** [comment]
LGTM

**Comment by tanuck** [comment]
👍

**Comment by yorkie** [comment]
If there is no objection from other collaborators in 6 hours, I will land this and bump version on NPM, thank you @tanuck :-)

/cc @Southern

**Comment by yorkie** [comment]
Bump version v0.2.5 on NPM, thank you @tanuck

**Comment by Southern** [comment]
Just getting around to reviewing this stuff. Looks good to me though. Thanks @tanuck and @yorkie!

**Pull request merged**
