### PR TITLE
Allow reading CA from memory as well as from a path in verify function

### PR DESCRIPTION
**Pull request by astitt-ripple**
This is a follow-up my prior PR https://github.com/Southern/node-x509/pull/44

It allows the caller to pass in buffers for the cert and ca instead of paths to the `verify` function.

Some JS code detects whether the cert and ca are files or buffers, and if they are files, reads them to a buffer first. I augmented the tests to verify any combination of file/buffer should work.

Also I found some cases where error code-paths would not fully clean up allocated memory or clear error statuses, those changes for the verify function are included here. I'm filing a separate PR with some similar cleanup to the parseCert function.

These modifications have been working very well for my use-case, and I would like to offer them back.

cc @Southern

### CODE REVIEW

**Comment by astitt-ripple** [comment]
@Southern Are there any changes you'd like to see here? No rush, just hoping to close out this PR if possible.

**Comment by astitt-ripple** [comment]
Closing due to inactivity.

@Southern feel free to re-open at any point if this is useful (or request changes). Thanks.

**Comment by Southern** [comment]
My apologies, @astitt-ripple. I got a new job right after I sent you the last message and have been totally swamped with it.

**Comment by astitt-ripple** [comment]
congrats on the new job @Southern!

**Comment by Southern** [comment]
Thanks! Hopefully I can get to this soon since this project at work is about to be released.

**Comment by scottmas** [comment]
@Southern Any update on this? This would be super handy. My use case involves sending a certificate through the http headers, thus it's pretty inconvenient to have to write it to file.

**Comment by Southern** [comment]
I’ll take a look at it as soon as possible, most likely this weekend. I
sincerely apologize to you all that have been waiting for this. Not only
did I get a new job, as previously mentioned, I was put in charge of
managing the entire project and have been extremely busy with that.

**Comment by scottmas** [comment]
No worries friend. Maintaining an open source project is a lot of work. I also just opened a new PR with a few tweaks (mostly following Javascript conventions a bit more)

**Comment by astitt-ripple** [comment]
Thanks for picking this up and polishing it off @scottmas 

I'm glad you find the added functionality useful.

**Pull request closed without merging**
