### PR TITLE
Updated version PR71 with formatting corrected

### PR DESCRIPTION
**Pull request by mbwhite**
This is the PR71 but with corrected formatting as per the discussion in PR71
Thank you to those who worked on fix; aim here is to get the fix merged as it is needed by
many projects

Signed-off-by: Matthew B. White <whitemat@uk.ibm.com>

### CODE REVIEW

**Comment by sstone1** [comment]
@yorkie could you look at this PR please?

**Comment by yorkie** [comment]
This looks good to me, thank you @mbwhite @sstone1 :)

**Comment by yorkie** [comment]
Released as `x509@0.3.4`, either.

**Comment by mbwhite** [comment]
Thank you @yorkie much appreciated!!

**Comment by mbwhite** [comment]
@yorkie   we've observed in large scale testing that some extra unicode characters are appearing... 

```
{ keyUsage: 'Certificate Sign',
  basicConstraints: 'CA:FALSE',
  subjectKeyIdentifier: 'D8:28:B4:C0:BC:92:4A:D3:C3:8C:54:6C:08:86:33:10:A6:8D:83:AE',
  authorityKeyIdentifier: 'keyid:C4:B3:FE:76:0D:E2:DE:3C:FC:75:FB:AE:55:86:04:F0:BB:7F:F6:01',
  subjectAlternativeName: 'DNS:Anils-MacBook-Pro.local',
  '1.2.3.4.5.6.7.8.1': '\u0004\u001a{"attrs":{"attr1":"val1"}}' }
```
This is the 'cert.extensions'.  To your knowledge is this a mistake in the certificate we're using or somehow related to the changes?

**Comment by kohend** [comment]
There's a bug in this PR: https://github.com/Southern/node-x509/blame/master/src/x509.cc#L280 should give the subject key algorithm as before and it gives the signature algorithm, same as https://github.com/Southern/node-x509/blame/master/src/x509.cc#L241

**Pull request merged**
