### PR TITLE
use nan@2.x to support nodejs4

### PR DESCRIPTION
**Pull request by yorkie**
Hey guys, within the Node.js has been released bound with nan@2.x, so that to work with our new platform, I just create this pr for this purpose.

/cc @Southern @Rush 
Thanks

### CODE REVIEW

**Comment by yorkie** [comment]
Merged because ci is happy

**Comment by yorkie** [comment]
And bumped new version x509@0.2.0, this should fix https://github.com/yorkie/node-x509/issues/3 either, /cc @ianare

**Comment by Southern** [comment]
@yorkie Awesome! Thanks for helping to continue to maintain this project!

**Comment by ianare** [comment]
Great thanks much! And sorry about the confusion, I put the bug report here because it's linked from NPM... I hadn't realized it was a fork.

**Comment by yorkie** [comment]
Never mind @ianare, because that fork repo is created by me before I was the collaborator here :)

**Pull request merged**
